image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Linux Build
    init: |
      sudo apt-get update
      sudo apt-get install -y build-essential cmake
      git config --global url."https://mirror.tuna.tsinghua.edu.cn/git/".insteadOf "https://github.com/"
    command: |
      make build-linux